### ISSUE TITLE
[BUG] Time literals are not formatted correctly

### ISSUE THREAD

**Issue by andiemontoyeah** [aws/amazon-documentdb-jdbc-driver#202]
## Environment
- DocumentDB JDBC driver version: v1.0.0
- DocumentDB server version: 3.6, 4.0
- OS: Any
- BI Tool or client name: Any
- BI Tool or client version: Any
- Java version (if known):  Java 8

---

## Problem Description
1. Steps to reproduce:   

- Connect to any database either using a Java application or BI tool. 
- Execute a query containing a time literal such as  `SELECT TIME '20:17:40' FROM collection` 
- Error occurs when retrieving result set. 

2. Expected behaviour:  Time value can be retrieved and displayed.
3. Actual behaviour: Query fails with error message - `Conversion between the source type (Integer) and the target type (Date) is not supported.`
4. Error message/stack trace:  
```
Conversion between the source type (Integer) and the target type (Date) is not supported.
java.sql.SQLException: Conversion between the source type (Integer) and the target type (Date) is not supported.
	at software.amazon.documentdb.jdbc.common.utilities.SqlError.createSQLException(SqlError.java:191)
	at software.amazon.documentdb.jdbc.DocumentDbAbstractResultSet.getValue(DocumentDbAbstractResultSet.java:173)
	at software.amazon.documentdb.jdbc.DocumentDbAbstractResultSet.getDate(DocumentDbAbstractResultSet.java:317)
	at software.amazon.documentdb.jdbc.DocumentDbAbstractResultSet.getTime(DocumentDbAbstractResultSet.java:335)
	at software.amazon.documentdb.jdbc.DocumentDbAbstractResultSet.getTime(DocumentDbAbstractResultSet.java:249)
Caused by: org.apache.commons.beanutils.ConversionException: Default conversion to java.sql.Date failed.
	at org.apache.commons.beanutils.converters.AbstractConverter.handleMissing(AbstractConverter.java:314)
	at org.apache.commons.beanutils.converters.AbstractConverter.handleError(AbstractConverter.java:269)
	at org.apache.commons.beanutils.converters.AbstractConverter.convert(AbstractConverter.java:177)
	at software.amazon.documentdb.jdbc.DocumentDbAbstractResultSet.getValue(DocumentDbAbstractResultSet.java:171
```
---

## Screenshots
- NA

---

## JDBC log
```
Created projection stages of pipeline.
Pipeline stages added: {$project: {'EXPR$0': {"$literal": 73060000}, _id: 0}}
Query 1926e6b5-33f4-4e5a-84a3-a2cfdcfaedc6: Took 2057 ms to translate query.
Sending command '{"aggregate": "collection", "pipeline": [{"$project": {"EXPR$0": {"$literal": 73060000}, "_id": 0}}], "cursor": {"batchSize": 2000}, "$db": "resultDatabase", "lsid": {"id": {"$binary": {"base64": "qpsgQdszQWOv3kr6DfGdVQ==", "subType": "04"}}}}' with request id 46 to database resultDatabase on connection [connectionId{localValue:9, serverValue:10}] to server localhost:55921
Execution of command with request id 46 completed successfully in 13.97 ms on connection [connectionId{localValue:9, serverValue:10}] to server localhost:55921
Query 1926e6b5-33f4-4e5a-84a3-a2cfdcfaedc6: Took 36 ms to execute query and retrieve first batch of results.
Query 1926e6b5-33f4-4e5a-84a3-a2cfdcfaedc6: Executed on collection collection with following pipeline operations: [{"$project": {"EXPR$0": {"$literal": 73060000}, "_id": 0}}]
Converting 'Integer' value '73060000' to type 'java.sql.Date'
    IntegerConverter cannot handle conversion to 'java.sql.Date'
    Conversion threw ConversionException: IntegerConverter cannot handle conversion to 'java.sql.Date'
    IntegerConverter cannot handle conversion to 'java.sql.Date'
Conversion between the source type (Integer) and the target type (Date) is not supported.
```

**Comment by andiemontoyeah** [comment]
Issue was addressed in #208. Fix was included in the [November release](https://github.com/aws/amazon-documentdb-jdbc-driver/releases/tag/v1.0.1).
